import { ViewStyle } from "react-native";

const styles = {
  app: {
    paddingTop: 15,
    paddingBottom: 30,
    height: '100%',
    backgroundColor: '#000000',
  },
  searchForm: {
    justifyContent: 'center',
    flexDirection: 'row',
  } as ViewStyle,
  searchButtonView: {
    height: 40,
    marginLeft: 12,
    marginTop: 3,
  },
  searchButton: {
    height: 48,
    padding: 4,
    fontSize: 18,
    borderRadius: 7,
  },
  searchInput: {
    fontSize: 16,
    padding: 8,
    backgroundColor: '#eee',
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 5,
    width: 260,
    height: 40,
  },
  tags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: 800,
  } as ViewStyle,
  tag: {
    margin: 5,
    backgroundColor: '#eee',
    padding: 5,
    paddingLeft: 11,
    paddingRight: 11,
    borderRadius: 5,
    borderColor: '#ddd',
    borderWidth: 1,
  },
  message: {
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 25,
    color: 'red',
    fontSize: 16,
    alignSelf: 'center',
  } as ViewStyle,
  loader: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    width: '100%',
    backgroundColor: '#000',
    height: '100%',
    opacity: 0.6,
    zIndex: 1,
    paddingBottom: 100,
  } as ViewStyle,
  AppFooter: {
    backgroundColor: '#ececec',
    padding: '10 0',
    position: 'absolute',
    width: '100%',
    bottom: 0,
    left: 0,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
  } as ViewStyle,
  AppFooterItem: {
    margin: '0 5',
    borderColor: '#999999',
    padding: 5,
    paddingLeft: 10,
    paddingRight: 10,
  } as ViewStyle,
  button: {
    marginTop: -20,
    marginBottom: 30,
    marginLeft: 'auto',
    marginRight: 'auto',
    backgroundColor: '#eee',
    padding: 5,
    paddingLeft: 11,
    paddingRight: 11,
    borderRadius: 5,
    borderColor: '#ddd',
    borderWidth: 1,
    width: 100,
  } as ViewStyle
}

export default styles
