import { ViewStyle } from "react-native";

const styles = {
  app: {
    paddingTop: 15,
    paddingBottom: 30,
    height: '100%',
    backgroundColor: '#000000',
  },
  searchForm: {
    justifyContent: 'center' as 'center',
    flexDirection: 'row' as 'row',
  },
  searchButtonView: {
    height: '40px',
    marginLeft: '12px',
    marginTop: '3px',
  },
  searchButton: {
    height: '48px',
    padding: '4px',
    fontSize: 18,
    borderRadius: 7,
  },
  searchInput: {
    fontSize: 16,
    padding: '8px',
    backgroundColor: '#eee',
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 5,
    width: '260px',
    height: '40px',
  },
  tags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: '15px',
    marginBottom: '15px',
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: '800px',
  } as ViewStyle,
  tag: {
    margin: '5px',
    backgroundColor: '#eee',
    padding: '5px',
    paddingLeft: '11px',
    paddingRight: '11px',
    borderRadius: 5,
    borderColor: '#ddd',
    borderWidth: 1,
  },
  message: {
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: '25px',
    color: 'red',
    fontSize: '16px',
    alignSelf: 'center',
  } as ViewStyle,
  loader: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    textAlign: 'center',
    position: 'absolute',
    top: 0,
    width: '100%',
    backgroundColor: '#000',
    height: '100%',
    opacity: 0.45,
    zIndex: 1,
    paddingBottom: '100px',
  } as ViewStyle,
  AppFooter: {
    backgroundColor: '#ececec',
    padding: '10px 0',
    position: 'absolute',
    width: '100%',
    bottom: 0,
    left: 0,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
  } as ViewStyle,
  AppFooterItem: {
    margin: '0 4px',
    borderLeftWidth: 1,
    borderColor: '#999999',
    padding: '6px',
  } as ViewStyle
}

export default styles
