import {ViewStyle, ImageStyle, TextStyle} from 'react-native'

const styles = {
  app: {
    paddingTop: 40,
    paddingBottom: 10,
    height: '100%',
    backgroundColor: '#000000',
    overflow: 'hidden',
  } as ViewStyle,
  button: {
    backgroundColor: '#eee',
    padding: 3,
    paddingLeft: 7,
    paddingRight: 7,
    borderRadius: 4,
    borderColor: '#ddd',
    borderWidth: 1,
    //width: 'fit-content',
    margin: 2,
  } as ViewStyle,
  buttonText: {
    fontFamily: 'Ubuntu Mono',
    fontSize: 16,
  } as TextStyle,
  searchForm: {
    justifyContent: 'center',
    flexDirection: 'row',
  } as ViewStyle,
  searchButtonView: {
    height: 40,
    marginLeft: 12,
    marginTop: 3,
  },
  searchButton: {
    height: 48,
    padding: 4,
    fontSize: 18,
    borderRadius: 7,
  },
  searchInput: {
    fontSize: 18,
    padding: 8,
    backgroundColor: '#f8f8f8',
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 5,
    width: 300,
    height: 36,
    fontFamily: 'Ubuntu Mono',
    //outline: 'none',
  },
  tags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 15,
    marginBottom: 25,
    marginLeft: 'auto',
    marginRight: 'auto',
    maxWidth: 800,
  } as ViewStyle,
  message: {
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 25,
    color: 'red',
    fontSize: 16,
    alignSelf: 'center',
  } as ViewStyle,
  loader: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    width: '100%',
    backgroundColor: '#FFF',
    height: '100%',
    opacity: 0.7,
    zIndex: 1,
    paddingBottom: 100,
  } as ViewStyle,
  footer: {
    backgroundColor: '#ececec',
    padding: 10,
    position: 'absolute',
    width: '100%',
    bottom: 0,
    left: 0,
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
  } as ViewStyle,
  footerLink: {
    borderWidth: 0,
    borderColor: '#ddd',
    padding: 5,
    paddingLeft: 10,
    paddingRight: 10,
  } as ViewStyle,
  pictureHolder: {
    flexDirection: 'column',
    position: 'relative',
  } as ViewStyle,
  picture: {
    marginBottom: 40,
  } as ImageStyle,
  pictureInfo: {
    position: 'absolute',
    bottom: '17%',
    flexDirection: 'row',
    alignSelf: 'center',
  } as ViewStyle,
}

export default styles
